spring.data.mongodb.uri=mongodb+srv://mayurpaul2502:pXLQguqs33ytSBXd@cluster0.l8m0o.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=journaldb
spring.data.monogodb.auto-index-creation=true